signavio/react-mentions

README.md

The more I play around with this component the more impressed I am. I love that the data can also be my own filtering scheme and it's not advertised in the documentation. Really well done on your part!

The data prop can also be a function, tell the world!

---

README.md
lib/Mention.js
lib/MentionsInput.js
lib/SuggestionsOverlay.js
package.json
src/Mention.jsx
src/MentionsInput.jsx

Hey there, we're quite enjoying using this library. I patched up a couple of things for our own sake, but hopefully they're helpful fixes. I fixed these two things:
First, the `onAdd` callback which is provided in the example ([see here](https://github.com/effektif/react-mentions/blob/5584cd70804d8a5acd3ad1925b92b07d559c60bc/gh-pages/views/examples/MultipleTriggerView.jsx#L43)) is potentially very useful, but was never actually called in the component source.
Secondly, I was getting an issue thanks to `displayTransform` being invoked [here](https://github.com/effektif/react-mentions/commit/bd16d946096f505c745edd2184ed5df7b3744dd3#diff-33f942b6199400cd55d6c8dd0f4a843cR499) when it was still the default value `null`.
Let me know if this is suitable to be pulled in. Thanks!

Fix some loose ends

---

src/utils.jsx

This Pull Request resolves #61

Only set selectionStartBeforeChange and/or selectionEndBeforeChange in applyChangeToValue if the values are undefined

---

README.md

Would these be correct specifications?

specify signatures of `data` and render Props

---

README.md
src/Mention.js
src/MentionsInput.js

Option to add a space after suggestion.

---

src/SuggestionsOverlay.js

Fix focus on suggestions list when navigate from  the keyboard.

Focus suggestions

---

gh-pages/views/examples/AdvancedView.js
gh-pages/views/examples/defaultStyle.js

modified AdvancedView example to show how to set styles for letting the suggestions overlay open above the cursor

Suggestions overlay above cursor example

---

src/MentionsInput.js
test/MentionsInput.spec.js

…from different mentions data sources (state updates overwrite each other)

fixed a bug when having multiple sync responses

---

.travis.yml
src/MentionsInput.js

fixed a JS error occuring because of stale focusIndex values

---

README.md
gh-pages/views/examples/CssModules.js
gh-pages/views/examples/Examples.js
gh-pages/views/examples/example.module.css
gh-pages/webpack.config.js
gh-pages/webpack.dev.config.js
package.json
yarn.lock

- upgrade substyle
- added example for css modules
- added docs

added css modules support

---

demo/src/examples/Examples.js
demo/src/examples/Scrollable.js
demo/src/examples/defaultStyle.js
src/MentionsInput.js

Fixes: #208, #210 
Adds an onScroll handler, whenever the input scrolls the highlighter scrolls as well.
[x] Passes tests
[x] Documentation added 
[ ] New tests to prove the scroll function
Credits to:
- RelocationOnline.com (My company, where we needed this fix)
- Max LaRue (Co-worker, that had a previous version fix)

Scrollable feature

---

demo/src/examples/SingleLine.js
demo/src/index.js
package.json
src/Highlighter.js
src/MentionsInput.js
src/SuggestionsOverlay.js
src/utils.js
test/utils.spec.js
yarn.lock

Fixes #240 and #199 
Also migrated to a more modern code style and removed some dead code.

Fix strict mode warnings and wrong plain text index

---

README.md
demo/src/examples/MultipleTrigger.js
src/Suggestion.js

feat: pass focused state to `renderSuggestion` (#270)

---

README.md
demo/src/examples/Advanced.js
package.json
src/MentionsInput.js
test/MentionsInput.spec.js
yarn.lock

feat: support for `inputRef` prop, which accepts a ref to be forwarded to the input

---

src/SuggestionsOverlay.js

fix(SuggestionsOverlay) LoadingIndicator style prop"

---

demo/src/examples/CssModules.js
demo/src/examples/defaultStyle.js
demo/src/examples/example.module.css
src/MentionsInput.js

Add example for colored mentions

---

package.json
yarn.lock

Hi!
I wanted to do some work testing this lib on windows. Needed to add in [`cross-env`](https://github.com/kentcdodds/cross-env) in order to develop on windows due to differences in setting enviroment variables across os. Could be helpful to others

cross os development

---

README.md

Hi, mainly I would like to thank you for this amazing repo 👍. 
I work for [Kontentino](https://www.kontentino.com/) and we are using it in our production  :)  Kontentino is making social media piece of 🍰and you helped us with your great work.
So this PR is just about adding us as a reference to the readme file 🚀.

Added Kontentino to using in production section

---

src/MentionsInput.js

Fixes #375.
I started coding on this before I realized that there's already a PR open to fix this issue (#506). But since the diff for my fix is much smaller, I still decided to open my own PR.
Feel free to close this if the other PR is better. Thanks!

Fix paste moving the cursor to the end of the input element

---

yarn.lock

Fixes error when executing yarn on windows console

chore(deps): yarn.lock update

---

demo/src/examples/CustomSuggestionsContainer.js
demo/src/examples/SingleLineIgnoringAccents.js
demo/src/examples/SuggestionPortal.js

Several small fixes to examples page
- Custom suggestions container label fixed (was "Custom mentions container")
- Custom suggestions container example made more noticeable
- Ignoring accents text edited
- Suggestion portal example container size fixed
**Checklist** (remove this list before you submit the PR)
* Are there tests for the new code? - No
* Does the code comply to our code conventions? - Yes
* Does the PR resolve the whole issue? - Inapplicable

chore: Examples page minor edits

---

src/LoadingIndicator.js

Fixes #259 
* useStyles from substyle need params
* useStyles() will error

fix: substyle need params

---

src/LoadingIndicator.js

Co-authored-by: quxinbo <quxinbo@baidu.com>
addressing a comment before merging to `master`

fix: substyle need params (#523)

---

.changeset/orange-bikes-care.md
src/Suggestion.js

Converts Suggestion.js from class component to functional component

refactor: `Suggestion.js` to functional component

---

.changeset/dull-monkeys-sin.md
src/SuggestionsOverlay.js

Fixes the typing of customeSuggestionsContainer in SuggestionsOverlay.js

fix: customSuggestionsContainer typing fixed in SuggestionsOverlay

---

.changeset/early-bags-destroy.md
CHANGELOG.md
package.json

Fixes improperly merged package.json info which is causing the release pipeline to fail.

Fix package.json properties for release
