signavio/react-mentions

- src/MentionsInput.jsx
- src/SuggestionsOverlay.jsx
Relying on the native event object is unreliable, and fails in firefox. this pr adds the necessary plumbing to provide the plainTextValue to the onChange callback when referenced in addMention, by passing it through the suggestion.
> Remove call to native event object

- src/MentionsInput.jsx
There's no check guaranteeing that there's enough space in window to display the suggestions list, so it can easily be cut off by window, especially on mobile:
I just check if suggestions would be displayed partially outside of window, if so I display them from right hand side of window and inwards instead. Works, although you might want a different solution.
> prevent suggestions being clipped by window

- package.json
- src/MentionsInput.jsx
MentionsInput.jsx requires react-dom but react-dom is only listed as a devDependency
which causes projects that use react-mentions to have react-dom in their dependencies list.
React 0.14 provides React.findDOMNode() which is all react-dom was used for in this project.
> Removing react-dom dependency

- src/MentionsInput.js
In Japanese IME, <kbd>shift</kbd>, <kbd>enter</kbd> and arrow keys are used to moving to each phrase and selecting conversion candidates while composing text, but it doesn't work fine.
> Fix text composition with Japanese IME

- src/MentionsInput.js
React 15.3.4 no longer ships the LinkedValueUtils. As the `valueLink` has been deprecated by React, we no longer support this prop.
> react 15.3.4 fix: drop valueLink support

- package.json
- src/Suggestion.js
Fix the 'unknown index property' error on the li as mentioned in #111 by adding index property as required on the Suggestion Component.
When the Suggestion Component gets rendered we use _.omit on the props and propTypes. 
By doing this we ignore the index property on the li tag.
> Fix unknow property index on li

- src/MentionsInput.js
Fix for issue #143 
When there is more than one `<Mention />` inside `<MentionsInput />`, the query keeps old results from other triggers (_# or @_ for example). 
The `suggestions` prop introduced in #142 wasn't being cleared.
> #143 Many <Mention />

- src/MentionsInput.js
- test/MentionsInput.spec.js
As requested by @frontendphil, here is the `allowSpaceInQuery` prop to toggle the behavior from #133 
- Tweaks the trigger regex if the prop is true to allow spaces when matching suggestions
- Touch-ups to the surrounding method body to reduce lint warnings
- Adds unit tests to cover the changes
- Set `value=""` to remove a console warning when running tests
> Add "allowSpaceInQuery" prop

- src/MentionsInput.js
- src/utils.js
- test/utils.spec.js
fixes a problem (#189) happening if existing mentions happen to be including in the matching sequence for a new mention, e.g. when keeping to type directly after an email mentions
> fix for #189

- src/MentionsInput.js
When MentionsInput is inside an iframe, document.activeElement returns iframe itself instead of actual input, so we need to dig deeper in that case.
> Make sure handleChange works within iframe

- src/Suggestion.js
Allow data.id to be an integer and not just string (#215).
Currently data.id pops warning when id is an integer (number).
> Allow id to be an integer (#215)

- src/MentionsInput.js
We ran into a very difficult to track bug that occurred only on production builds of our app.
React threw an invariant error which causes React rendering to break entirely (https://reactjs.org/docs/error-decoder.html?invariant=137&args[]=input&args[]=)
After digging deeper into our code, we found out that a `<MentionsInput />` component from `react-mentions` was the cause of this error. This error only occurred when `singleLine` was true, which makes sense because the `invariant` error is about `input` elements.
Digging deeper into the `react-mentions` code led us to [this line](https://github.com/signavio/react-mentions/blob/master/src/MentionsInput.js#L125): 
```
let props = omit(this.props, 'style', keys(MentionsInput.propTypes))
```
Omitting the props with the `propType` keys does not …
> Fix breaking React invariant error on production builds when using singleLine true

- demo/src/index.js
- src/Highlighter.js
- src/SuggestionsOverlay.js
- src/utils.js
Fixes #ABC
Simple edit to avoid having suggestions with the same react key, appending mention type before the id in the SuggestionsOverlay rendering loop.
**Checklist** (remove this list before you submit the PR)
* Are there tests for the new code?
No
* Does the code comply to our code conventions?
Yes
* Does the PR resolve the whole issue?
It does
**Additional review hints** (remove this list before you submit the PR)
* Besides the code review, what should the reviewer test?
* Are there any edge cases?
* Do you have any test files or test set-up?
* Could your changes cause side effects elsewhere in the code base?
Nope
> Avoid suggestions ID clashing for different mention types

- src/MentionsInput.js
Fixes #274
This makes it so that the selectionStart and selectionEnd are set even if it is being selected in the "composition" mode in android. This was causing the cursor jumping issue described in https://github.com/signavio/react-mentions/issues/274 because if you selected a point in the text then selected some point after it (eg. the next line), it would double up the text because it thought the cursor was still at the first point.
> Fix cursor jumping on android

- src/MentionsInput.js
Lots of users reported a crash on https://app.amazingmarvin.com after I updated to react 16.8.  It was not very easy to reproduce, but in some cases in MentionsInput.js: setState calls updateSuggestionsPosition which calls setState which calls updateSuggestionsPosition... until it crashes.
This PR prevents such recursive calls to setState.
I made it so that only `componentDidUpdate` calls where something other than `suggestionPosition` changes trigger a call to `updateSuggestionsPosition`.
**Checklist**
* Are there tests for the new code? I don't know how to do this.
* Does the code comply to our code conventions? I'm not sure. I don't know where these are.
Feel free to leave this open for a bit since I (and Marvin users) will be testing …
> Prevent crash from recursive calls to setState.

- src/MentionsInput.js
Fixes #325 
Add `allowSpaceInQuery` to propTypes so it gets stripped out of the props that get passed down to the textarea.
> Add allowSpaceInQuery to propTypes

- src/Suggestion.js
Fixes #277 
Allows ID field in mention data to be 0. Falsy check would previously error out if id field was zero- checks for undefined instead to avoid this behaviour
> Allow ID field in Mention data to be 0

- demo/src/examples/ExperimentalCutCopyPaste.js
- src/MentionsInput.js
- src/MentionsInput.spec.js
Fixes #348 
~I added a fallback to use `window.clipboardData` when `event.clipboardData` is not defined, which is the case in IE 11, when the new experimental copy and paste feature is used.~
Following the investigation in this PR, I disabled the new cut, copy, paste mechanism for browsers whose events do not have `clipboardData` attached to the event. This concerns mostly IE. 
In IE 11 the `clipboardData` object is attached to `window` and only supports mime type `text`. Therefore, the new mechanism will not work anyway as it makes use of two different mime types.
How to test?
1. Open IE 11
2. Go to https://react-mentions.wolf-pack.now.sh
3. Scroll to the EXPERIMENTAL section
4. Copy the text with mentions
5. Paste it in the next input
> fix: Support experimental copy & paste in IE 11

- demo/src/examples/CssModules.js
Fixes CSS Modules example
**What did you change (functionally and technically)?**
In the course of implementing react-mentions with (S)CSS modules, I found that we also need to provide a base class name for the substyled-component to generate its expected class names from.
This fixes that in the example.
> Fix CSS Modules example

- src/MentionsInput.js
- src/MentionsInput.spec.js
Fixes #366
- removes carriage returns from pasted strings
- adds a test
The problem was that strings that were copied from MS word or google docs included invisible carriage returns, additionally to line feeds.
> removes carriage returns from pasted strings

- src/MentionsInput.js
It is discovered that compositionEnd event will not fire if all of the following conditions are matched
1. Use Chrome / Firefox
2. Use Sucheng input method
3. select suggestion by 'enter' which the display item ends with a character that only requires one char to input for the method, for example, '手'，'田'，'水'，'口'，'人'
This issue leads to suggestion item like '所有人' ends up to become '@[所有人](all)人', which expected result should be '@[所有人](all)'
> Workaround of browsers not firing compositionEnd event

- src/SuggestionsOverlay.js
this keeps the overlay clickable and fixes #410
> fix: make sure the default position is absolute when using pure inline styles

- src/utils/markupToRegex.js
- src/utils/markupToRegex.spec.js
Fixes #429 
The function "markupToRegex" at line 9 https://github.com/signavio/react-mentions/blob/master/src/utils/markupToRegex.js#L9
Refer to display, not to id
the result of 
markupToRegex("[tag id=id /]") 
was returning 
/[tag\ id=([^i]+?)\ /]/
escaping all "i" from the id
> Wrong conversion of markup to regex

- README.md
- demo/src/examples/Advanced.js
- demo/src/examples/AsyncGithubUserMentions.js
- demo/src/examples/BottomGuard.js
- demo/src/examples/CssModules.js
- demo/src/examples/CutCopyPaste.js
- demo/src/examples/MultipleTrigger.js
- demo/src/examples/Scrollable.js
- demo/src/examples/SingleLine.js
- demo/src/examples/SingleLineIgnoringAccents.js
- demo/src/examples/SuggestionPortal.js
- src/MentionsInput.js
- src/Suggestion.js
- src/SuggestionsOverlay.js
- src/utils/getSuggestionHtmlId.js
- src/utils/getSuggestionHtmlId.spec.js
- src/utils/index.js
Fixes #451
This PR contains mainly minor changes: required markup for assistive technologies, but some important logical changes were also required.
* Added new property `a11ySuggestionsListLabel ` of `MentionsInput`. This string will be exposed to screen readers when suggestions popup will appear. Demos also were updated to demonstrate it's usage.
* Text input should have specific markup to expose its association with suggestions list. This markup should appear only when the suggestions list is visible. Because of that `isOpen` prop of `SuggestionsOverlay` was created. Suggestions list will appear only when isOpen set to `true`. The value for this property is now calculated in `MentionsInput` with a new method `isOpen()`. In this way, we can strictly link text input properties with the …
> Support of assistive technologies

- demo/src/examples/Emojis.js
I submit a simple modification of the example page.
The API for getting the list of emoji returns `ERR_NAME_NOT_RESOLVED`. (The API may be outdated.)
As a result, `Emoji support` cannot be used properly.
Since I couldn't find any other APIs that can be used without a secret key, I modified it so that the `Emoji support` can be used correctly by retrieving it from the JSON of the published emoji list.
You'll see that when you type two or more characters following `:`, a list of Emoji selections will appear.
Since this is just the example page modification, no test code has been added.
> Fix a problem with `emoji support` not working on the example page

- README.md
Adding an official recommendation for how to test `<MentionsInput>`.
closes #330
> chore: added a note on testing <MentionsInput>

- src/MentionsInput.js
Fixes #444 
Added `ev.stopPropagation()` in handleKeyDown method of `MentionsInput.js` when the keyDown event is handled by react-mentions (e.g. for `RETURN` key the stopPropagation will be called as this event is handled by react-mentions to select the focused suggestion)
> Stopping propagation of handleKeyDown event

- demo/src/examples/BottomGuard.js
- src/MentionsInput.js
Currently, mentions can be rendered on top of the input/textarea only if the space below is not enough.
For my usecase, I wanted the mentions to be rendered on top of it always. So I added a boolean to do this.
> add the ability to force mentions to be rendered on top of the input

- src/MentionsInput.js
- src/SuggestionsOverlay.js
Fixes #556
I forwarded the `right` calculation to the `SuggestionsOverlay`. It's calculated already in `updateSuggestionsPosition`
```
// guard for mentions suggestions list clipped by right edge of window
if (left + suggestions.offsetWidth > this.containerElement.offsetWidth) {
position.right = 0
```
When upgrading from 3.3.2 to 4.0.0 the `style` was replaced explicitly by `left` & `top` which resulted in this regression. See here https://github.com/signavio/react-mentions/compare/v3.3.2...v4.0.1#diff-00403e8131ecb98542c8244e62a5d7da189e273b086d554fa319d4403a7844fcL62-R85
> fix positioning for overlay near the right side of a textarea/input

- demo/src/examples/Examples.js
I'm working on several IME related bugs including https://github.com/signavio/react-mentions/issues/164
This pull request is a preparation for a proper fix.
Could you merge this one first and get it deployed to https://react-mentions.vercel.app/ so our users can test it with different languages?
Thanks!
> Add fictional character names in Asian languages for testing.

- src/MentionsInput.js
Fixes #564
See the bug report. When highlighting a mention and typing a character, the cursor is now placed at the correct position.
> fix: Take newly typed characters into account when a mention is deleted

- src/MentionsInput.js
Fixes #501 
In the current implementation, the highlighted text position stays fixed when scrolled in a disabled state. Added a fix for the same.
> fix: scroll issue in disabled mode

- README.md
Revised Readme to recommend yarn instead of npm for working on component
> fix: npm start converted to yarn start

- README.md
- src/MentionsInput.js
Fix forceSuggestionsAboveCursor when suggestionsPortalHost is not being used. Mistake in https://github.com/signavio/react-mentions/pull/449.
Here's a quick repro: https://codesandbox.io/s/react-mentions-forcesuggestionsabovecursor-bug-bq1x0?file=/src/App.js
Resize your browser window so that the suggestions do not fit above the input field to trigger the bug.
Let me know if you need anything else for this fix. Thanks!
By the way, the links on [the releases page](https://github.com/signavio/react-mentions/releases) are not clickable. They render like this: `http://git+https/github.com/signavio/react-mentions/issues/492`. Is this intentional?
> fix: forceSuggestionsAboveCursor when suggestionsPortalHost is not being used

- .changeset/poor-monkeys-doubt.md
- src/SuggestionsOverlay.js
Converts SuggestionsOverlay.js from class component to functional component
> refactor: SuggestionsOverlay.js functional component

- .changeset/sharp-toys-jam.md
- src/MentionsInput.js
Fixes #658 
**Checklist** (remove this list before you submit the PR)
* Are there tests for the new code? ❌ (but there were none before)
* Does the code comply to our code conventions? ✅ (incl changeset)
* Does the PR resolve the whole issue?
* Seems like the actual textarea update in React 18 happens a bit later and therefor we need to set it after the next render
> fix: selection should be correctly set after pasting text

- .changeset/silver-boats-build.md
- src/SuggestionsOverlay.js
Fixes [#663](https://github.com/signavio/react-mentions/issues/653)
It was found that this problem occurred when the suggestionOverlay was refactored into a hook. [see this commit](https://github.com/signavio/react-mentions/commit/834240e5d4f17e0a9a0e63757dd4e72977330fa6)
Originally, the scroll position would be updated in componentDidUpdate, but in the hook version, it only does this in the initial effect.
so I fix effect's dependency to ensure scroll can be updated in correct time.
> fix: fix scroll into view automatically

- .changeset/smart-eyes-kiss.md
- src/SuggestionsOverlay.js
Fixes issue: [674](https://github.com/signavio/react-mentions/issues/674)
When attempting to scroll through the custom container elements an error would occur. I found that the custom container was being rendered inside the unordered list instead of around it. Rearranged the elements
**Checklist** (remove this list before you submit the PR)
* Are there tests for the new code? No
* Does the code comply to our code conventions? Yes
* Does the PR resolve the whole issue? Yes
How to test:
- Add `maxHeight` and `overflowY: 'auto'` to the list styling in SuggestionsOverlay.js
- Run react-mentions and open on localhost
- Scroll down to the custom container element
- Pull up the suggestions list with the '@' button
- Try scrolling through the …
> fix: fixes scroll into view in custom container elements

- .changeset/popular-ladybugs-jog.md
- src/MentionsInput.js
Fixes bug introduced by [here](https://github.com/signavio/react-mentions/commit/3f40576fcf57580f7b49640585c5a19c4f79e30e#diff-b93f5486e33dabca047d7813cfda3b850e21823fdb3dae6ad48f6b2f7662ba8eL362) where content is pasted twice - you can view this behavior on https://react-mentions.vercel.app/
> Fix double-paste bug

- .changeset/healthy-ways-protect.md
- src/MentionsInput.js
Hi team 👋 
After I upgraded to `4.4.8` I was experiencing some layout shifts when rendering the input as a `textarea` inside of a modal. This was caused by the `autoFocus` being turned on when `textarea` is rendered. `autoFocus` should be passed using props since this is not a default behavior.
> Remove default autoFocus from textarea

- .changeset/khaki-dryers-kneel.md
- src/MentionsInput.js
Fixes suggestions not showing while composing issue
---
<br/>
> fix: suggestions not showing while composing

- .changeset/seven-kangaroos-remember.md
- .gitignore
- src/MentionsInput.js
The fix for native undo/redo (only a plain text) in case the input was not focused before the operation.
Steps to reproduce:
- input any text to MentionInput
- focus something else
- press `ctrl`+`z`/`cmd`+`z`
Technically, the problem happens, because for such undo/redo operations `onChange` handler is called before `onSelect`, hence `this.state.selectionStart` and `this.state.selectionEnd` are `null` and the next value is calculated incorrectly, based on what there was before the operation and the value that should be set after one
> Fixed native undo/redo

- .changeset/popular-toys-wait.md
- .gitignore
- README.md
- demo/src/examples/CustomInputComponent.js
- demo/src/examples/Examples.js
- demo/src/examples/example.module.css
- src/MentionsInput.js
- src/MentionsInput.spec.js
Fixes https://github.com/signavio/react-mentions/issues/622
It will help to use `react-mentions` with already existing in the design system components
> Allow the use of a custom input component
